### PR TITLE
Explicitly declare value for android:exported

### PR DESCRIPTION
**Pull request by imondal007**
Fix for install error on Android 12

### CODE REVIEW

**Comment by hariks789** [comment]
@darron1217 First of all thanks for the work you have done with this package.
Will you be able to merge this pull request?

**Comment by hariks-mm** [comment]
@darron1217 Thanks a lot mate.
Just a gentle reminder for you to release this version on npm when you get some free time

**Comment by andidev** [comment]
@darron1217 please can you release this? its been a really long time now.

**Comment by LightKnight3r** [comment]
hi all, can you show me the way to build from develop branch? It always shows this error:

* What went wrong:
A problem occurred evaluating project ':@darron1217_react-native-background-geolocation'.
> Could not read script '/node_modules/@darron1217/react-native-background-geolocation/android/common/VERSIONS.gradle' as it does not exist.

**Comment by mcastillo86** [comment]
when will this be released? In my case I cannot publish in Google play due to current requirement of API 31 and this package is not helping on that.

**Comment by darron1217** [comment]
@mcastillo86 I've published new version. Please check

**Comment by mcastillo86** [comment]
thanks @darron1217! However, there is an issue with the new version. It has already been reported here: #28

**Comment by littlecircle0730** [comment]
@darron1217 I think the common file in android is missing for 0.6.7 version.

**Comment by gigby** [comment]
@darron1217 0.6.7 version really has no common file

`
A problem occurred evaluating project ':darron1217_react-native-background-geolocation'.
> Could not read script '/Users/gigby/Documents/work/migraineinsight/node_modules/@darron1217/react-native-background-geolocation/android/common/VERSIONS.gradle' as it does not exist.
`

**Comment by lucaspereirasouzat** [comment]
this is still happen here

**Comment by RuFang-21** [comment]
same to me, still happen the error (could not read script '.......common/VERSIONS.grandle' as it does not exist
do you guys have any solution ?

Thanks

**Comment by gigby** [comment]
@RuFang-21 
I tested this library on targetSdk=31. It doesn't work (there is no fatal but many errors in log output). It doesn't fit to target sdk 31 requirements.
Summarizing all these issues, the best solution is not using this libarary any more. It has been abandoned again :D

**Comment by RuFang-21** [comment]
@gigby Did you have any library recommened for this background-geo-location? 
Thanks first !

**Comment by LightKnight3r** [comment]
Hi all, maybe this will be usefull. Im using this fork repo: @hariks789/react-native-background-geolocation

**Comment by gigby** [comment]
@RuFang-21 I decided to start using transistorsoft/react-native-background-geolocation. It's well maintaining for long time.

**Comment by RuFang-21** [comment]
> Hi all, maybe this will be usefull. Im using this fork repo: @hariks789/react-native-background-geolocation

Thank you so much !

**Comment by RuFang-21** [comment]
> @RuFang-21 I decided to start using transistorsoft/react-native-background-geolocation. It's well maintaining for long time.

Ya, I think this would be better ~

**Pull request merged**
